FROM composer:2.6.5

WORKDIR /app
COPY . .

# PostgreSQL
RUN apk --no-cache add postgresql-dev
RUN docker-php-ext-install pdo_pgsql

# Redis
RUN apk --no-cache add autoconf gcc g++
RUN pecl install redis
RUN docker-php-ext-enable redis

# PHP Exif
RUN docker-php-ext-install exif

# PHP GD
RUN apk --no-cache add zlib-dev libpng-dev libwebp-dev libjpeg-turbo-dev freetype-dev
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp 
RUN docker-php-ext-install gd

# PHP.ini
RUN printf "# photobank php ini settings\n\
upload_max_filesize = 128M\n\
post_max_size = 128M\n\
" > $PHP_INI_DIR/php.ini

RUN composer install

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]